In [1]:
#Numpy :- import numpy liabrary
import numpy as np

In [2]:
#array:-
#one Dimensional
b=np.array([1,2,3,4,5,6])
#two Dimensional
a=np.array([[1,2,3],[4,5,6]])
print(" one dimensional array :")
print(b)
print(" two dimensional array :")
print(a)


 one dimensional array :
[1 2 3 4 5 6]
 two dimensional array :
[[1 2 3]
 [4 5 6]]


In [3]:
#format :-the standard binary file format
#Shape :- the number of elements in each dimension
a=np.array([[1,2,3],[4,5,6]])
print("shape of a {}".format(a.shape))


shape of a (2, 3)


In [4]:
#ndim :- represents the number of dimensions of the array
a=np.array([[1,2,3],[4,5,6]])
print("ndim {}".format(a.ndim))

ndim 2


In [5]:
#size:-calculate the total elements or values  in the given array
a=np.array([[1,2,3],[4,5,6]])
print("size {}".format(a.size))

size 6


In [6]:
#dtype:-describes the fixed-size block of memory
a=np.array([[1,2,3],[4,5,6]])
print("dtype {}".format(a.dtype))

dtype int64


In [7]:
#itemsize :- returns the size (in bytes) of each element of a NumPy array
a=np.array([[1,2,3],[4,5,6]])
print("itemsize {}".format(a.itemsize))

itemsize 8


In [8]:
#data :- 
a=np.array([[1,2,3],[4,5,6]])
print("data {}".format(a.data))

data <memory at 0x7fe248acc110>


In [9]:
#sum :-returns the sum of array elements over the specified axis
a=np.array([[1,2,3],[4,5,6]])
print(a.sum())


21


In [11]:
#multiplication :- multiplication of two array
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]
mul=np.dot(A,B)
print("multiplication :")
print(mul)

multiplication :
[[16 19]
 [26 31]]


In [12]:
#addition :-performs element-wise addition
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]
ad=np.add(A,B)
print("addition :")
print(ad)

addition :
[[ 5  7]
 [ 8 10]]


In [13]:
#reshape :- changing the shape of an array
a=np.array([1,2,3,4,5,6])
re=a.reshape(2,3)
print(re)

[[1 2 3]
 [4 5 6]]


In [14]:
#maximum :- ind the element-wise maximum of array elements
a=np.array([1,2,3,4,5,6])
print("maximum is ",a.max())

maximum is  6


In [15]:
#maximum along the axis
re=np.array([[1,2,3],[4,5,6]])
print("maximum is ",re.max(axis=1))

maximum is  [3 6]


In [16]:
# minimum :-find the element-wise minimum of array elements
a=np.array([1,2,3,4,5,6])
print("minimum is ",a.min())

minimum is  1


In [18]:
#minimum along the axis
re=np.array([[1,2,3],[4,5,6]])
print("minimum is ",re.min(axis=0))

minimum is  [1 2 3]


In [19]:
# square root:-calculate the positive square root of a number or the elements of an array
re=np.array([[1,4,9],[16,25,36]])
print(np.sqrt(re))

[[1. 2. 3.]
 [4. 5. 6.]]


In [20]:
#standard deviation :-calculates the standard deviation of given data along a specified axis
re=np.array([[1,4,9],[16,25,36]])
print("standard deviation ",np.std(re))

standard deviation  12.212243401148248


In [22]:
# merging :-merge two arrays
# vstack :-Stack arrays in sequence vertically (row wise)
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
v=np.vstack((a,b))
print("vertical :")
print(v)

vertical :
[[1 2]
 [4 5]
 [8 7]
 [5 4]]


In [23]:
#horizontal :- combines a sequence of arrays
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
print("horizontal :")
print(h)

horizontal :
[[1 2 8 7]
 [4 5 5 4]]


In [24]:
#arange :- produces an array of sequential numbers within a given interval
a=np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
a=np.arange(0,20,2,float)
print("data type: ",a.dtype)

data type:  float64


In [26]:
#linspace :-allows you to create evenly spaced arrays with a specified number of elements
a=np.linspace(0,20,11)
print(a)
print("data type: ",a.dtype)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
data type:  float64


In [27]:
#transpose :- moving the rows data to the column and columns data to the rows
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
ht=h.T
print(ht)

[[1 4]
 [2 5]
 [8 5]
 [7 4]]


In [28]:
#nditer :- provides many flexible ways to visit all the elements of one or more arrays in a systematic fashion
for i in np.nditer(ht):
    print("ele :",i)

ele : 1
ele : 2
ele : 8
ele : 7
ele : 4
ele : 5
ele : 5
ele : 4


In [29]:
#hsplit :- split an array into multiple sub-arrays horizontally (column-wise)
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
h1=np.hsplit(h,2)
print(h1)

[array([[1, 2],
       [4, 5]]), array([[8, 7],
       [5, 4]])]


In [30]:
#vsplit :- split an array into multiple sub-arrays vertically (row-wise)
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
h1=np.vsplit(h,2)
print(h1)

[array([[1, 2, 8, 7]]), array([[4, 5, 5, 4]])]
